/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guessthenumber;

public class App {

    public static void main(String[] args) {
        mainMenu menu = new mainMenu();
        menu.setTitle("Guess the number");
        menu.setVisible(true);
        menu.setLocation(100, 100);
        menu.setResizable(false);
    }
}
